apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: meddeb/petclinic:v7
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: svc-ptclinic
spec:
  selector:
    app: petclinic
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30102
